POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Lucas",
    "lastName": "Silva",
    "email" : "lucas@email.com",
    "age" : 25
}

###

GET http://localhost:3000/users

### 

GET http://localhost:3000/clientes

### 

POST http://localhost:3000/clientes
Content-Type: application/json

{
    "nome": "Lucas",
    "cidade": "iguatu",
    "userId": 2,
    "email": "lucas@email.com",
    "idade" : 25
}